services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__PostgreSQL=Host=db;Username=postgres;Password=password;Database=markov
      - Binance__ApiKey=${BINANCE_API_KEY}
      - Binance__ApiSecret=${BINANCE_API_SECRET}

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=markov
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d markov"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: